#!/bin/sh
# Change resolution based on arguments
MODE="desktop"

command -v xrandr >/dev/null || {
    echo "$(basename $0): xrandr command not found." 1>&2
    exit 1
}

# if there is arguments, read them
if test $# -ge 1; then
    MODE=$1
fi

if test $MODE = "desktop"; then
    xrandr --output LVDS1 --auto --output VGA1 --auto --right-of LVDS1
elif test $MODE = "laptop"; then
    xrandr --output VGA1 --off --output LVDS1 --auto
fi
