#!/bin/sh -e

if [ "$1" = "--detail" ]; then
	cat /etc/issue
	exit 0
fi

if [ -n "$DISTRO" ]; then
	# skip down to the bottom
	true
elif which lsb_release >/dev/null 2>&1; then
	if [ "$1" = "--detail" ]; then
		lsb_release -a 2>/dev/null
		exit 0
	fi
	# If lsb_release is available, use it
	r=$(lsb_release -s -d)
	if echo "$r" | grep -qs "^Ubuntu .*\..*\..*$"; then
		# Use the -d if an Ubuntu LTS
		DISTRO="$r"
	else
		# But for other distros the description
		# is too long, so build from -i and -r
		i=$(lsb_release -s -i)
		r=$(lsb_release -s -r)
		DISTRO="$i $r"
	fi
elif [ -r "/etc/palm-build-info" ]; then
	# Palm Pre hack
	DISTRO=$(grep "^PRODUCT_VERSION_STRING=Palm " /etc/palm-build-info | sed "s/^.*=Palm //")
elif [ -r "/etc/issue" ]; then
	# Otherwise, grab part of /etc/issue, ideally the distro and version
	DISTRO=$(grep -m1 "^[A-Za-z]" /etc/issue | sed "s/ [^0-9]* / /" | awk '{print $1 " " $2}')
else
	DISTRO="Unknown"
fi

printf "%s " "$DISTRO"
